kind: pipeline
name: default

workspace:
  base: /go
  path: leetcode/github.com/kylesliu/awesome-golang-algorithm

steps:
  - name: test
    image: golang
    commands:
      - go get
      - go test