language: go

go:
  - 1.9.x
  - 1.10.x
  - 1.11.x
  - 1.12.x
  - 1.13.x

# whitelist
branches:
  only:
  - master
#  - stable

script:
- go get -t -v ./...
#- go vet ./...
- bash ./test.sh

after_success:
- bash <(curl -s https://codecov.io/bash)
