name: Go
on:
  pull_request:
  push:
    branches:
      - master
jobs:

  build:
    name: Test Solution Cases
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run:  go mod download

    - name: Test lcof
      run: make test-lcof
      
    - name: Test leetcode solution
      run: make test-leetcode